import { User, DashboardStats } from "./types";

export const currentUser: User = {
  id: "usr_001",
  fullName: "Sarah Nakato",
  email: "sarah.nakato@email.com",
  phone: "+256772843901",
  nin: "CM98041234AB7X",
  accountType: "individual",
  kycStatus: "verified",
  location: "Kampala",
  profilePic: undefined,
  createdAt: "2025-11-15",
};

export const dashboardStats: DashboardStats = {
  activeLoans: 1,
  applicationsPending: 1,
  newOffers: 2,
  walletBalance: 842500,
};

// ─── Notifications ───

import type {
  Notification,
  AdminStats,
  AdminUser,
  AdminLoan,
  AdminApplication,
  LenderProfile,
  LenderDashboardStats,
  BorrowerActivity,
} from "./types";

export const notifications: Notification[] = [
  {
    id: "notif_001",
    title: "New Loan Offer",
    message:
      "Kampala Capital Partners has sent you a loan offer of UGX 5,000,000 at 16% APR.",
    type: "offer",
    read: false,
    createdAt: "2026-04-20T14:30:00",
  },
  {
    id: "notif_002",
    title: "Payment Reminder",
    message: "Your next instalment of UGX 350,000 is due on 01 May 2026.",
    type: "payment",
    read: false,
    createdAt: "2026-04-19T09:00:00",
  },
  {
    id: "notif_003",
    title: "Application Update",
    message:
      "Your loan application LF-2026-00847 is now under review by 3 lenders.",
    type: "status",
    read: true,
    createdAt: "2026-04-18T16:45:00",
  },
  {
    id: "notif_004",
    title: "KYC Verified",
    message:
      "Your identity documents have been verified successfully. You can now apply for loans.",
    type: "system",
    read: true,
    createdAt: "2026-04-15T11:20:00",
  },
  {
    id: "notif_005",
    title: "Offer Accepted",
    message:
      "You have accepted the loan offer from Uganda Micro Lenders. Funds will be disbursed within 24hrs.",
    type: "offer",
    read: true,
    createdAt: "2026-04-12T13:00:00",
  },
  {
    id: "notif_006",
    title: "Payment Successful",
    message:
      "Your instalment of UGX 350,000 has been successfully processed via MTN MoMo.",
    type: "payment",
    read: true,
    createdAt: "2026-04-01T10:15:00",
  },
];

// ─── Admin Dummy Data ───

export const adminStats: AdminStats = {
  totalUsers: 2847,
  activeLoans: 412,
  pendingApplications: 67,
  totalDisbursed: 18500000000,
  monthlyRevenue: 420000000,
  defaultRate: 3.2,
};

export const adminUsers: AdminUser[] = [
  {
    id: "usr_001",
    fullName: "Sarah Nakato",
    email: "sarah@mpola.ug",
    phone: "+256 700 123 456",
    accountType: "individual",
    kycStatus: "verified",
    activeLoans: 1,
    totalBorrowed: 15000000,
    joinedAt: "2025-11-15",
    status: "active",
  },
  {
    id: "usr_002",
    fullName: "James Okello",
    email: "james.okello@mpola.ug",
    phone: "+256 771 234 567",
    accountType: "individual",
    kycStatus: "verified",
    activeLoans: 2,
    totalBorrowed: 28000000,
    joinedAt: "2025-09-22",
    status: "active",
  },
  {
    id: "usr_003",
    fullName: "Namukasa Textiles Ltd",
    email: "info@namukasa.co.ug",
    phone: "+256 312 456 789",
    accountType: "business",
    kycStatus: "pending",
    activeLoans: 0,
    totalBorrowed: 0,
    joinedAt: "2026-04-10",
    status: "active",
  },
  {
    id: "usr_004",
    fullName: "Peter Ssemakula",
    email: "peter.s@email.com",
    phone: "+256 756 678 901",
    accountType: "individual",
    kycStatus: "rejected",
    activeLoans: 0,
    totalBorrowed: 5000000,
    joinedAt: "2026-01-05",
    status: "suspended",
  },
  {
    id: "usr_005",
    fullName: "Grace Achieng",
    email: "grace@achiengsalon.com",
    phone: "+256 780 789 012",
    accountType: "business",
    kycStatus: "verified",
    activeLoans: 1,
    totalBorrowed: 42000000,
    joinedAt: "2025-06-18",
    status: "active",
  },
  {
    id: "usr_006",
    fullName: "Daniel Mugisha",
    email: "dmugisha@outlook.com",
    phone: "+256 701 890 123",
    accountType: "individual",
    kycStatus: "verified",
    activeLoans: 0,
    totalBorrowed: 8000000,
    joinedAt: "2025-12-01",
    status: "active",
  },
];

export const adminLoans: AdminLoan[] = [
  {
    id: "aln_001",
    reference: "LF-2026-00412",
    borrowerName: "Sarah Nakato",
    lenderName: "Kampala Capital Partners",
    amount: 5000000,
    interestRate: 16,
    status: "active",
    disbursedAt: "2026-01-15",
    nextPaymentDate: "2026-05-01",
    paidInstalments: 3,
    totalInstalments: 18,
  },
  {
    id: "aln_002",
    reference: "LF-2026-00389",
    borrowerName: "James Okello",
    lenderName: "Uganda Micro Lenders",
    amount: 12000000,
    interestRate: 18,
    status: "active",
    disbursedAt: "2026-02-01",
    nextPaymentDate: "2026-05-01",
    paidInstalments: 2,
    totalInstalments: 24,
  },
  {
    id: "aln_003",
    reference: "LF-2025-00198",
    borrowerName: "Grace Achieng",
    lenderName: "East Africa Finance",
    amount: 25000000,
    interestRate: 14,
    status: "active",
    disbursedAt: "2025-10-15",
    nextPaymentDate: "2026-05-15",
    paidInstalments: 6,
    totalInstalments: 36,
  },
  {
    id: "aln_004",
    reference: "LF-2025-00150",
    borrowerName: "Peter Ssemakula",
    lenderName: "Kampala Capital Partners",
    amount: 5000000,
    interestRate: 20,
    status: "overdue",
    disbursedAt: "2025-08-01",
    nextPaymentDate: "2026-03-01",
    paidInstalments: 5,
    totalInstalments: 12,
  },
  {
    id: "aln_005",
    reference: "LF-2025-00095",
    borrowerName: "Daniel Mugisha",
    lenderName: "Centenary MFI",
    amount: 8000000,
    interestRate: 15,
    status: "completed",
    disbursedAt: "2025-01-15",
    nextPaymentDate: "-",
    paidInstalments: 12,
    totalInstalments: 12,
  },
];

export const adminApplications: AdminApplication[] = [
  {
    id: "aap_001",
    reference: "LF-2026-00847",
    borrowerName: "Sarah Nakato",
    amount: 8000000,
    loanType: "business",
    status: "reviewing_offers",
    offersCount: 3,
    createdAt: "2026-04-18",
  },
  {
    id: "aap_002",
    reference: "LF-2026-00852",
    borrowerName: "Namukasa Textiles Ltd",
    amount: 50000000,
    loanType: "business",
    status: "submitted",
    offersCount: 0,
    createdAt: "2026-04-19",
  },
  {
    id: "aap_003",
    reference: "LF-2026-00855",
    borrowerName: "James Okello",
    amount: 3000000,
    loanType: "personal",
    status: "approved",
    offersCount: 2,
    createdAt: "2026-04-17",
  },
  {
    id: "aap_004",
    reference: "LF-2026-00860",
    borrowerName: "Grace Achieng",
    amount: 15000000,
    loanType: "business",
    status: "submitted",
    offersCount: 0,
    createdAt: "2026-04-20",
  },
];

// ─── Lender Portal Data ───

export const lenderProfile: LenderProfile = {
  id: "lnd_001",
  fullName: "David Mugisha",
  email: "david@mugisha-capital.ug",
  phone: "+256772100842",
  accountType: "individual",
  nin: "CM98041234AB7X",
  tier: "premium",
  createdAt: "2024-06-15",
};

export const lenderDashboardStats: LenderDashboardStats = {
  totalDeployed: 92400000,
  activeLoans: 18,
  monthlyReturns: 1240000,
  repaymentRate: 98.6,
};

export const borrowerActivities: BorrowerActivity[] = [
  {
    id: "ba_001",
    borrowerName: "Sarah Nakato",
    borrowerInitials: "SN",
    location: "Kampala",
    verified: true,
    amount: 8000000,
    loanType: "Business",
    status: "New Application",
  },
  {
    id: "ba_002",
    borrowerName: "James Okello",
    borrowerInitials: "JO",
    location: "Kampala",
    verified: true,
    amount: 3500000,
    loanType: "Personal",
    status: "Reviewing",
  },
  {
    id: "ba_003",
    borrowerName: "Brenda Achieng",
    borrowerInitials: "BA",
    location: "Kampala",
    verified: true,
    amount: 12000000,
    loanType: "Business",
    status: "Offer Sent",
  },
  {
    id: "ba_004",
    borrowerName: "Ismail Ssemakadde",
    borrowerInitials: "IS",
    location: "Kampala",
    verified: true,
    amount: 2000000,
    loanType: "Personal",
    status: "Repaying",
  },
  {
    id: "ba_005",
    borrowerName: "Christine Tumuheirwe",
    borrowerInitials: "CT",
    location: "Kampala",
    verified: true,
    amount: 5500000,
    loanType: "Business",
    status: "Accepted",
  },
];
