import {
  User,
  LoanApplication,
  LoanOffer,
  ActiveLoan,
  Instalment,
  Guarantor,
  Lender,
  DashboardStats,
} from "./types";

export const currentUser: User = {
  id: "usr_001",
  fullName: "Sarah Nakato",
  email: "sarah.nakato@email.com",
  phone: "+256772843901",
  nin: "CM98041234AB7X",
  accountType: "individual",
  kycStatus: "verified",
  location: "Kampala",
  profilePic: undefined,
  createdAt: "2025-11-15",
};

export const dashboardStats: DashboardStats = {
  activeLoans: 1,
  applicationsPending: 1,
  newOffers: 2,
  walletBalance: 842500,
};

export const activeLoan: ActiveLoan = {
  id: "loan_001",
  reference: "LF-2026-00621",
  amount: 5000000,
  lenderName: "Kampala Capital Partners",
  interestRate: 13.5,
  totalInstalments: 12,
  paidInstalments: 4,
  monthlyPayment: 458200,
  nextPaymentDate: "2026-05-01",
  nextPaymentAmount: 458200,
};

export const applications: LoanApplication[] = [
  {
    id: "app_001",
    reference: "LF-2026-00847",
    amount: 8000000,
    duration: 18,
    loanType: "business",
    purpose: "Business expansion",
    description:
      "Expanding my salon in Ntinda — adding 2 stations and new equipment",
    status: "reviewing_offers",
    offersCount: 3,
    createdAt: "2026-04-10",
  },
  {
    id: "app_002",
    reference: "LF-2026-00621",
    amount: 5000000,
    duration: 12,
    loanType: "personal",
    purpose: "Personal use",
    status: "active",
    offersCount: 1,
    createdAt: "2026-01-05",
  },
  {
    id: "app_003",
    reference: "LF-2025-04418",
    amount: 2500000,
    duration: 6,
    loanType: "personal",
    purpose: "Education",
    status: "completed",
    offersCount: 0,
    createdAt: "2025-08-20",
  },
];

export const loanOffers: LoanOffer[] = [
  {
    id: "offer_001",
    applicationId: "app_001",
    lenderName: "Stanbic Micro-Finance",
    lenderInitials: "SM",
    rating: 4.8,
    reviewCount: 412,
    interestRate: 11.9,
    monthlyPayment: 487485,
    totalRepayable: 8774727,
    approvalTime: "24 hrs",
    offerSentAt: "15 Apr 2026",
    features: [
      "No early repayment penalty",
      "Flexible payment dates",
      "Dedicated account manager",
    ],
    isBestRate: true,
    isFeatured: true,
    status: "pending",
  },
  {
    id: "offer_002",
    applicationId: "app_001",
    lenderName: "Kampala Capital Partners",
    lenderInitials: "KC",
    rating: 4.6,
    reviewCount: 287,
    interestRate: 13.5,
    monthlyPayment: 493449,
    totalRepayable: 8882083,
    approvalTime: "48 hrs",
    offerSentAt: "15 Apr 2026",
    features: [
      "Grace period: 30 days",
      "SMS payment reminders",
      "Refinance option after 6 months",
    ],
    status: "pending",
  },
  {
    id: "offer_003",
    applicationId: "app_001",
    lenderName: "Pearl Credit Uganda",
    lenderInitials: "PC",
    rating: 4.4,
    reviewCount: 198,
    interestRate: 14.2,
    monthlyPayment: 496071,
    totalRepayable: 8929287,
    approvalTime: "72 hrs",
    offerSentAt: "16 Apr 2026",
    features: ["Competitive business loans", "Partial payments allowed"],
    status: "pending",
  },
];

export const lenders: Lender[] = [
  {
    id: "lender_001",
    name: "Stanbic Micro-Finance",
    initials: "SM",
    rating: 4.8,
    reviewCount: 412,
    approvalTime: "24 hrs",
    minRate: 11.9,
    estimatedMonthly: 487485,
    features: [
      "No early repayment penalty",
      "Flexible payment dates",
      "Dedicated account manager",
    ],
    isFeatured: true,
    isBestRate: true,
  },
  {
    id: "lender_002",
    name: "Kampala Capital Partners",
    initials: "KC",
    rating: 4.6,
    reviewCount: 287,
    approvalTime: "48 hrs",
    minRate: 13.5,
    estimatedMonthly: 493449,
    features: [
      "Grace period: 30 days",
      "SMS payment reminders",
      "Refinance option after 6 months",
    ],
  },
  {
    id: "lender_003",
    name: "Pearl Credit Uganda",
    initials: "PC",
    rating: 4.4,
    reviewCount: 198,
    approvalTime: "72 hrs",
    minRate: 14.2,
    estimatedMonthly: 496071,
    features: ["Competitive business loans", "Partial payments allowed"],
  },
  {
    id: "lender_004",
    name: "Equator Finance Ltd.",
    initials: "EF",
    rating: 4.7,
    reviewCount: 356,
    approvalTime: "36 hrs",
    minRate: 12.8,
    estimatedMonthly: 490835,
    features: ["Women-owned business priority", "Free financial advisory"],
  },
];

export const guarantors: Guarantor[] = [
  {
    id: "guar_001",
    fullName: "Grace Namuli",
    relationship: "Sibling",
    phone: "+25672118402",
    email: "grace.namuli@gmail.com",
    status: "confirmed",
    confirmedAt: "17 Apr 2026 · 11:42 EAT",
  },
  {
    id: "guar_002",
    fullName: "Peter Mbabazi",
    relationship: "Business Partner",
    phone: "+25602994118",
    email: "peter.m@mbabazi-partners.ug",
    status: "confirmed",
    confirmedAt: "17 Apr 2026 · 11:42 EAT",
  },
];

export const instalments: Instalment[] = [
  {
    number: 1,
    dueDate: "1 Jan 2026",
    amount: 458200,
    status: "paid",
    paidOn: "1 Jan 2026",
  },
  {
    number: 2,
    dueDate: "1 Feb 2026",
    amount: 458200,
    status: "paid",
    paidOn: "31 Jan 2026",
  },
  {
    number: 3,
    dueDate: "1 Mar 2026",
    amount: 458200,
    status: "paid",
    paidOn: "2 Mar 2026",
  },
  {
    number: 4,
    dueDate: "1 Apr 2026",
    amount: 458200,
    status: "paid",
    paidOn: "1 Apr 2026",
  },
  { number: 5, dueDate: "1 May 2026", amount: 458200, status: "due" },
  { number: 6, dueDate: "1 Jun 2026", amount: 458200, status: "upcoming" },
  { number: 7, dueDate: "1 Jul 2026", amount: 458200, status: "upcoming" },
  { number: 8, dueDate: "1 Aug 2026", amount: 458200, status: "upcoming" },
  { number: 9, dueDate: "1 Sep 2026", amount: 458200, status: "upcoming" },
  { number: 10, dueDate: "1 Oct 2026", amount: 458200, status: "upcoming" },
  { number: 11, dueDate: "1 Nov 2026", amount: 458200, status: "upcoming" },
  { number: 12, dueDate: "1 Dec 2026", amount: 458200, status: "upcoming" },
];

// ─── Notifications ───

import type {
  Notification,
  AdminStats,
  AdminUser,
  AdminLoan,
  AdminApplication,
  LenderProfile,
  LenderDashboardStats,
  BorrowerActivity,
  MarketplaceBorrower,
  BorrowerProfile,
  LenderEarnings,
} from "./types";

export const notifications: Notification[] = [
  {
    id: "notif_001",
    title: "New Loan Offer",
    message:
      "Kampala Capital Partners has sent you a loan offer of UGX 5,000,000 at 16% APR.",
    type: "offer",
    read: false,
    createdAt: "2026-04-20T14:30:00",
  },
  {
    id: "notif_002",
    title: "Payment Reminder",
    message: "Your next instalment of UGX 350,000 is due on 01 May 2026.",
    type: "payment",
    read: false,
    createdAt: "2026-04-19T09:00:00",
  },
  {
    id: "notif_003",
    title: "Application Update",
    message:
      "Your loan application LF-2026-00847 is now under review by 3 lenders.",
    type: "status",
    read: true,
    createdAt: "2026-04-18T16:45:00",
  },
  {
    id: "notif_004",
    title: "KYC Verified",
    message:
      "Your identity documents have been verified successfully. You can now apply for loans.",
    type: "system",
    read: true,
    createdAt: "2026-04-15T11:20:00",
  },
  {
    id: "notif_005",
    title: "Offer Accepted",
    message:
      "You have accepted the loan offer from Uganda Micro Lenders. Funds will be disbursed within 24hrs.",
    type: "offer",
    read: true,
    createdAt: "2026-04-12T13:00:00",
  },
  {
    id: "notif_006",
    title: "Payment Successful",
    message:
      "Your instalment of UGX 350,000 has been successfully processed via MTN MoMo.",
    type: "payment",
    read: true,
    createdAt: "2026-04-01T10:15:00",
  },
];

// ─── Admin Dummy Data ───

export const adminStats: AdminStats = {
  totalUsers: 2847,
  activeLoans: 412,
  pendingApplications: 67,
  totalDisbursed: 18500000000,
  monthlyRevenue: 420000000,
  defaultRate: 3.2,
};

export const adminUsers: AdminUser[] = [
  {
    id: "usr_001",
    fullName: "Sarah Nakato",
    email: "sarah@mpola.ug",
    phone: "+256 700 123 456",
    accountType: "individual",
    kycStatus: "verified",
    activeLoans: 1,
    totalBorrowed: 15000000,
    joinedAt: "2025-11-15",
    status: "active",
  },
  {
    id: "usr_002",
    fullName: "James Okello",
    email: "james.okello@mpola.ug",
    phone: "+256 771 234 567",
    accountType: "individual",
    kycStatus: "verified",
    activeLoans: 2,
    totalBorrowed: 28000000,
    joinedAt: "2025-09-22",
    status: "active",
  },
  {
    id: "usr_003",
    fullName: "Namukasa Textiles Ltd",
    email: "info@namukasa.co.ug",
    phone: "+256 312 456 789",
    accountType: "business",
    kycStatus: "pending",
    activeLoans: 0,
    totalBorrowed: 0,
    joinedAt: "2026-04-10",
    status: "active",
  },
  {
    id: "usr_004",
    fullName: "Peter Ssemakula",
    email: "peter.s@email.com",
    phone: "+256 756 678 901",
    accountType: "individual",
    kycStatus: "rejected",
    activeLoans: 0,
    totalBorrowed: 5000000,
    joinedAt: "2026-01-05",
    status: "suspended",
  },
  {
    id: "usr_005",
    fullName: "Grace Achieng",
    email: "grace@achiengsalon.com",
    phone: "+256 780 789 012",
    accountType: "business",
    kycStatus: "verified",
    activeLoans: 1,
    totalBorrowed: 42000000,
    joinedAt: "2025-06-18",
    status: "active",
  },
  {
    id: "usr_006",
    fullName: "Daniel Mugisha",
    email: "dmugisha@outlook.com",
    phone: "+256 701 890 123",
    accountType: "individual",
    kycStatus: "verified",
    activeLoans: 0,
    totalBorrowed: 8000000,
    joinedAt: "2025-12-01",
    status: "active",
  },
];

export const adminLoans: AdminLoan[] = [
  {
    id: "aln_001",
    reference: "LF-2026-00412",
    borrowerName: "Sarah Nakato",
    lenderName: "Kampala Capital Partners",
    amount: 5000000,
    interestRate: 16,
    status: "active",
    disbursedAt: "2026-01-15",
    nextPaymentDate: "2026-05-01",
    paidInstalments: 3,
    totalInstalments: 18,
  },
  {
    id: "aln_002",
    reference: "LF-2026-00389",
    borrowerName: "James Okello",
    lenderName: "Uganda Micro Lenders",
    amount: 12000000,
    interestRate: 18,
    status: "active",
    disbursedAt: "2026-02-01",
    nextPaymentDate: "2026-05-01",
    paidInstalments: 2,
    totalInstalments: 24,
  },
  {
    id: "aln_003",
    reference: "LF-2025-00198",
    borrowerName: "Grace Achieng",
    lenderName: "East Africa Finance",
    amount: 25000000,
    interestRate: 14,
    status: "active",
    disbursedAt: "2025-10-15",
    nextPaymentDate: "2026-05-15",
    paidInstalments: 6,
    totalInstalments: 36,
  },
  {
    id: "aln_004",
    reference: "LF-2025-00150",
    borrowerName: "Peter Ssemakula",
    lenderName: "Kampala Capital Partners",
    amount: 5000000,
    interestRate: 20,
    status: "overdue",
    disbursedAt: "2025-08-01",
    nextPaymentDate: "2026-03-01",
    paidInstalments: 5,
    totalInstalments: 12,
  },
  {
    id: "aln_005",
    reference: "LF-2025-00095",
    borrowerName: "Daniel Mugisha",
    lenderName: "Centenary MFI",
    amount: 8000000,
    interestRate: 15,
    status: "completed",
    disbursedAt: "2025-01-15",
    nextPaymentDate: "-",
    paidInstalments: 12,
    totalInstalments: 12,
  },
];

export const adminApplications: AdminApplication[] = [
  {
    id: "aap_001",
    reference: "LF-2026-00847",
    borrowerName: "Sarah Nakato",
    amount: 8000000,
    loanType: "business",
    status: "reviewing_offers",
    offersCount: 3,
    createdAt: "2026-04-18",
  },
  {
    id: "aap_002",
    reference: "LF-2026-00852",
    borrowerName: "Namukasa Textiles Ltd",
    amount: 50000000,
    loanType: "business",
    status: "submitted",
    offersCount: 0,
    createdAt: "2026-04-19",
  },
  {
    id: "aap_003",
    reference: "LF-2026-00855",
    borrowerName: "James Okello",
    amount: 3000000,
    loanType: "personal",
    status: "approved",
    offersCount: 2,
    createdAt: "2026-04-17",
  },
  {
    id: "aap_004",
    reference: "LF-2026-00860",
    borrowerName: "Grace Achieng",
    amount: 15000000,
    loanType: "business",
    status: "submitted",
    offersCount: 0,
    createdAt: "2026-04-20",
  },
];

// ─── Lender Portal Data ───

export const lenderProfile: LenderProfile = {
  id: "lnd_001",
  fullName: "David Mugisha",
  email: "david@mugisha-capital.ug",
  phone: "+256772100842",
  accountType: "individual",
  nin: "CM98041234AB7X",
  tier: "premium",
  createdAt: "2024-06-15",
};

export const lenderDashboardStats: LenderDashboardStats = {
  totalDeployed: 92400000,
  activeLoans: 18,
  monthlyReturns: 1240000,
  repaymentRate: 98.6,
};

export const borrowerActivities: BorrowerActivity[] = [
  {
    id: "ba_001",
    borrowerName: "Sarah Nakato",
    borrowerInitials: "SN",
    location: "Kampala",
    verified: true,
    amount: 8000000,
    loanType: "Business",
    status: "New Application",
  },
  {
    id: "ba_002",
    borrowerName: "James Okello",
    borrowerInitials: "JO",
    location: "Kampala",
    verified: true,
    amount: 3500000,
    loanType: "Personal",
    status: "Reviewing",
  },
  {
    id: "ba_003",
    borrowerName: "Brenda Achieng",
    borrowerInitials: "BA",
    location: "Kampala",
    verified: true,
    amount: 12000000,
    loanType: "Business",
    status: "Offer Sent",
  },
  {
    id: "ba_004",
    borrowerName: "Ismail Ssemakadde",
    borrowerInitials: "IS",
    location: "Kampala",
    verified: true,
    amount: 2000000,
    loanType: "Personal",
    status: "Repaying",
  },
  {
    id: "ba_005",
    borrowerName: "Christine Tumuheirwe",
    borrowerInitials: "CT",
    location: "Kampala",
    verified: true,
    amount: 5500000,
    loanType: "Business",
    status: "Accepted",
  },
];

export const marketplaceBorrowers: MarketplaceBorrower[] = [
  {
    id: "mb_001",
    name: "Sarah N.",
    initials: "S",
    location: "Kampala",
    kycVerified: true,
    loanType: "Business",
    amount: 8000000,
    duration: 18,
    purpose: "Salon expansion in Ntinda",
    documents: 6,
    guarantorsConfirmed: 2,
  },
  {
    id: "mb_002",
    name: "James O.",
    initials: "J",
    location: "Jinja",
    kycVerified: true,
    loanType: "Personal",
    amount: 3500000,
    duration: 12,
    purpose: "Boda-boda purchase",
    documents: 4,
    guarantorsConfirmed: 2,
  },
  {
    id: "mb_003",
    name: "Brenda A.",
    initials: "B",
    location: "Kampala",
    kycVerified: true,
    loanType: "Business",
    amount: 12000000,
    duration: 24,
    purpose: "Inventory for retail shop",
    documents: 7,
    guarantorsConfirmed: 2,
  },
  {
    id: "mb_004",
    name: "Ismail S.",
    initials: "I",
    location: "Entebbe",
    kycVerified: true,
    loanType: "Personal",
    amount: 2000000,
    duration: 6,
    purpose: "Medical expenses",
    documents: 3,
    guarantorsConfirmed: 1,
  },
  {
    id: "mb_005",
    name: "Christine T.",
    initials: "C",
    location: "Mbarara",
    kycVerified: true,
    loanType: "Business",
    amount: 5500000,
    duration: 18,
    purpose: "Dairy farming expansion",
    documents: 5,
    guarantorsConfirmed: 2,
  },
  {
    id: "mb_006",
    name: "Moses K.",
    initials: "M",
    location: "Gulu",
    kycVerified: true,
    loanType: "Business",
    amount: 7000000,
    duration: 24,
    purpose: "Hardware store inventory",
    documents: 6,
    guarantorsConfirmed: 2,
  },
];

export const borrowerProfileData: BorrowerProfile = {
  id: "bp_001",
  name: "Sarah N.",
  initials: "SN",
  location: "Kampala, Uganda",
  memberSince: "Jan 2024",
  kycVerified: true,
  requestingAmount: 8000000,
  duration: 18,
  loanType: "Business",
  purpose:
    "Expanding my salon in Ntinda — I've been operating for 3 years with steady growth. This loan will fund 2 additional stations, new equipment (dryers, washbasins), and 3 months of working capital while the new space ramps up.",
  monthlyIncome: 2800000,
  existingObligations: 420000,
  disposableIncome: 2380000,
  dtiRatio: 15,
  dtiRating: "Excellent",
  creditScore: 742,
  creditRating: "GOOD",
  paymentHistory: "Excellent",
  creditUtilization: "Low (22%)",
  creditAge: "2.4 years",
  recentEnquiries: 1,
  applications: 3,
  loansCompleted: "1 on time",
  currentOffers: 2,
  appliedAt: "Apr 15, 2026",
  responseTime: "Within 2 hrs",
  riskLevel: "Low Risk",
  riskDescription:
    "Strong repayment history, low DTI, stable income, 2 confirmed guarantors.",
};

export const lenderEarnings: LenderEarnings = {
  totalEarnings: 8420000,
  thisMonth: 1240000,
  avgYield: 14.2,
  monthlyData: [
    { month: "Nov", amount: 850000 },
    { month: "Dec", amount: 920000 },
    { month: "Jan", amount: 1050000 },
    { month: "Feb", amount: 1100000 },
    { month: "Mar", amount: 1180000 },
    { month: "Apr", amount: 1240000 },
  ],
};
