"use client";

import type { ReactNode } from "react";
import { toast } from "sonner";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useTransactionDetail } from "@/hooks/use-wallet";
import { api } from "@/lib/api";
import { formatCurrency, formatDuration, formatRate } from "@/lib/format";
import type { TransactionDetail, WalletTransactionType } from "@/lib/types";

const TYPE_LABEL: Record<WalletTransactionType, string> = {
  deposit: "Deposit",
  withdrawal: "Withdrawal",
  repayment: "Loan Repayment",
  disbursement: "Loan Disbursement",
  top_up: "Top-up",
};

const FEE_CATEGORY_LABEL: Record<string, string> = {
  mobile_money_withdrawal: "Mobile money withdrawal fee",
  bank_withdrawal: "Bank transfer fee",
  loan_disbursement: "Disbursement fee",
  loan_repayment: "Repayment fee",
  late_fee_platform_cut: "Late fee (platform share)",
};

function formatDateTime(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString("en-UG", {
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function receiptLines(tx: TransactionDetail): [string, string][] {
  const lines: [string, string][] = [
    ["Amount", `${tx.direction === "credit" ? "+" : "-"}${formatCurrency(tx.amount)}`],
    ["Type", TYPE_LABEL[tx.type]],
    ["Status", tx.status.charAt(0).toUpperCase() + tx.status.slice(1)],
    ["Description", tx.description || TYPE_LABEL[tx.type]],
    ["Transaction ID", tx.id],
  ];
  if (tx.reference) lines.push(["Reference", tx.reference]);
  lines.push(["Date & Time", formatDateTime(tx.created_at)]);
  if (tx.counterparty && !tx.loan) lines.push(["Counterparty", tx.counterparty]);
  if (tx.total_fee != null) {
    if (tx.fee_category) lines.push(["Fee type", FEE_CATEGORY_LABEL[tx.fee_category] ?? tx.fee_category]);
    if (tx.platform_fee) lines.push(["Platform fee", formatCurrency(tx.platform_fee)]);
    if (tx.provider_fee) lines.push(["Provider fee", formatCurrency(tx.provider_fee)]);
    lines.push(["Total charged", formatCurrency(tx.total_fee)]);
  } else {
    lines.push(["Platform fee", "No fee on this transaction"]);
  }
  if (tx.loan) {
    lines.push(["Loan ID", tx.loan.id]);
    lines.push(["Principal", formatCurrency(tx.loan.amount)]);
    lines.push(["Interest Rate", formatRate(tx.loan.interest_rate)]);
    lines.push(["Duration", formatDuration(tx.loan.duration, tx.loan.duration_days)]);
    if (tx.loan.borrower_name) lines.push(["Borrower", tx.loan.borrower_name]);
    if (tx.loan.lender_name) lines.push(["Lender", tx.loan.lender_name]);
    if (tx.repayment) {
      lines.push([
        "Instalment",
        `#${tx.repayment.instalment_number} of ${tx.loan.total_instalments}`,
      ]);
    }
  }
  return lines;
}

function receiptText(tx: TransactionDetail): string {
  const header = `MPOLA — PAYMENT RECEIPT\n${"=".repeat(28)}\n`;
  const body = receiptLines(tx)
    .map(([label, value]) => `${label}: ${value}`)
    .join("\n");
  return `${header}\n${body}\n`;
}

function receiptHtml(tx: TransactionDetail): string {
  const rows = receiptLines(tx)
    .map(
      ([label, value]) =>
        `<tr><td style="padding:6px 12px;color:#6b7280;font-size:13px;">${label}</td><td style="padding:6px 12px;color:#1B2B3A;font-size:13px;font-weight:600;text-align:right;">${value}</td></tr>`,
    )
    .join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>Mpola Receipt ${tx.id}</title></head>
<body style="font-family:Arial,Helvetica,sans-serif;background:#f3f4f6;padding:32px;">
<div style="max-width:480px;margin:0 auto;background:#fff;border-radius:16px;padding:32px;border:1px solid #e5e7eb;">
<h1 style="color:#149D8E;font-size:20px;margin:0 0 4px;">Mpola</h1>
<p style="color:#6b7280;font-size:13px;margin:0 0 24px;">Payment Receipt</p>
<p style="font-size:28px;font-weight:800;margin:0;color:${tx.direction === "credit" ? "#059669" : "#ea580c"};">
${tx.direction === "credit" ? "+" : "-"}${formatCurrency(tx.amount)}
</p>
<table style="width:100%;border-collapse:collapse;margin-top:20px;">${rows}</table>
<p style="color:#9ca3af;font-size:11px;margin-top:24px;">Generated by Mpola — this receipt reflects the transaction record at time of download.</p>
</div>
</body></html>`;
}

function downloadReceipt(tx: TransactionDetail) {
  const blob = new Blob([receiptHtml(tx)], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `mpola-receipt-${tx.id}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

async function shareReceipt(tx: TransactionDetail) {
  const text = receiptText(tx);
  if (typeof navigator !== "undefined" && navigator.share) {
    try {
      await navigator.share({ title: "Mpola Receipt", text });
    } catch {
      // user cancelled the share sheet — no-op
    }
    return;
  }
  if (typeof navigator !== "undefined" && navigator.clipboard) {
    await navigator.clipboard.writeText(text);
    toast.success("Receipt copied to clipboard");
  }
}

/** Loan-related transactions (repayment/disbursement) have a real,
 * backend-generated PDF receipt — prefer that over the generic HTML one,
 * which stays as the fallback for deposits/withdrawals (no PDF for those). */
async function handleDownload(tx: TransactionDetail) {
  try {
    if (tx.type === "repayment" && tx.repayment) {
      await api.downloadRepaymentReceipt(tx.repayment.id);
      return;
    }
    if (tx.type === "disbursement" && tx.loan) {
      await api.downloadDisbursementReceipt(tx.loan.id);
      return;
    }
  } catch {
    // fall through to the generic receipt below
  }
  downloadReceipt(tx);
}

function Row({ label, value, mono }: { label: string; value: ReactNode; mono?: boolean }) {
  return (
    <div className="flex items-start justify-between gap-4 py-2">
      <span className="text-sm text-gray-500 shrink-0">{label}</span>
      <span
        className={`text-sm font-medium text-[#1B2B3A] dark:text-white text-right ${mono ? "font-mono text-xs break-all" : ""}`}
      >
        {value}
      </span>
    </div>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div className="rounded-xl border border-gray-200 dark:border-gray-800 p-4">
      <p className="text-xs font-bold uppercase tracking-wider text-gray-400 mb-1">{title}</p>
      <div className="divide-y divide-gray-100 dark:divide-gray-800">{children}</div>
    </div>
  );
}

export function TransactionDetailModal({
  transactionId,
  onClose,
}: {
  transactionId: string | null;
  onClose: () => void;
}) {
  const { data: tx, isLoading } = useTransactionDetail(transactionId);

  return (
    <Dialog open={!!transactionId} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-lg max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-[#1B2B3A] dark:text-white">
            Transaction Details
          </DialogTitle>
        </DialogHeader>

        {isLoading || !tx ? (
          <div className="space-y-3 py-4">
            {[1, 2, 3].map((i) => (
              <div key={i} className="h-12 rounded-lg bg-gray-100 dark:bg-gray-800 animate-pulse" />
            ))}
          </div>
        ) : (
          <div className="space-y-4">
            {/* Amount hero */}
            <div className="text-center py-3">
              <p
                className={`text-3xl font-black ${
                  tx.direction === "credit" ? "text-emerald-600" : "text-orange-500"
                }`}
              >
                {tx.direction === "credit" ? "+" : "-"}
                {formatCurrency(tx.amount)}
              </p>
              <p className="text-sm text-gray-500 mt-1">
                {tx.description || TYPE_LABEL[tx.type]}
              </p>
              <div className="flex items-center justify-center gap-2 mt-2">
                <Badge variant="outline">{TYPE_LABEL[tx.type]}</Badge>
                <Badge
                  variant="outline"
                  className={
                    tx.status === "completed"
                      ? "bg-emerald-50 text-emerald-600 border-emerald-200"
                      : tx.status === "pending"
                        ? "bg-gray-100 text-gray-500 border-gray-200"
                        : "bg-red-50 text-red-500 border-red-200"
                  }
                >
                  {tx.status.charAt(0).toUpperCase() + tx.status.slice(1)}
                </Badge>
              </div>
            </div>

            <Section title="Transaction Info">
              <Row label="Transaction ID" value={tx.id} mono />
              {tx.reference && <Row label="Reference" value={tx.reference} mono />}
              <Row label="Date &amp; Time" value={formatDateTime(tx.created_at)} />
              {tx.counterparty && !tx.loan && (
                <Row label="Counterparty" value={tx.counterparty} />
              )}
            </Section>

            <Section title="Charges">
              {tx.total_fee != null ? (
                <>
                  {tx.fee_category && (
                    <Row label="Fee type" value={FEE_CATEGORY_LABEL[tx.fee_category] ?? tx.fee_category} />
                  )}
                  {tx.platform_fee != null && tx.platform_fee > 0 && (
                    <Row label="Platform fee" value={formatCurrency(tx.platform_fee)} />
                  )}
                  {tx.provider_fee != null && tx.provider_fee > 0 && (
                    <Row label="Provider fee" value={formatCurrency(tx.provider_fee)} />
                  )}
                  <Row
                    label="Total charged"
                    value={<span className="text-[#149D8E]">{formatCurrency(tx.total_fee)}</span>}
                  />
                </>
              ) : (
                <Row label="Platform fee" value="No fee on this transaction" />
              )}
            </Section>

            {tx.loan && (
              <Section title="Loan Details">
                <Row label="Loan ID" value={tx.loan.id} mono />
                <Row label="Principal" value={formatCurrency(tx.loan.amount)} />
                <Row label="Interest Rate" value={formatRate(tx.loan.interest_rate)} />
                <Row label="Duration" value={formatDuration(tx.loan.duration, tx.loan.duration_days)} />
                <Row
                  label="Status"
                  value={tx.loan.status.charAt(0).toUpperCase() + tx.loan.status.slice(1)}
                />
                {tx.loan.borrower_name && (
                  <Row label="Borrower" value={tx.loan.borrower_name} />
                )}
                {tx.loan.lender_name && <Row label="Lender" value={tx.loan.lender_name} />}
                {tx.repayment && (
                  <Row
                    label="Instalment"
                    value={`#${tx.repayment.instalment_number} of ${tx.loan.total_instalments}`}
                  />
                )}
                <Row
                  label="Repaid so far"
                  value={`${formatCurrency(tx.loan.total_paid)} of ${formatCurrency(tx.loan.total_repayable)}`}
                />
              </Section>
            )}

            <div className="flex gap-3 pt-1">
              <Button
                variant="outline"
                className="flex-1"
                onClick={() => handleDownload(tx)}
              >
                Download Receipt
              </Button>
              <Button
                variant="outline"
                className="flex-1"
                onClick={() => shareReceipt(tx)}
              >
                Share
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
